### ISSUE TITLE
Usage without module loader?

### ISSUE THREAD

**Issue by qodeboy** [rhyek/vue2-selectize#1]
Hello, is it possible to use this component without module loader/compiler? I'm using plain old javascript that is simply included on page, so I need a way to include your component. Any way you can provide built js files or instructions how I can build manually?

**Comment by rhyek** [comment]
@qodeboy I haven't really tested use as a global library. Sorry for not answering sooner. If you haven't worked it out yet, I am now tracking the built files in this repository. You can use `dist/vue2-selectize.js`. Test it out and let me know if it works for you.

**Comment by qodeboy** [comment]
Thanks for the update, but I was able to work it out by building own component using your code as a reference. 

For anyone interested, here is my solution: https://gist.github.com/qodeboy/4a67fbb21a80518ca0d9dcdeb900bc7a. As a bonus, it keeps track on options and update itself if they were changed.

**Comment by rhyek** [comment]
> For anyone interested, here is my solution: https://gist.github.com/qodeboy/4a67fbb21a80518ca0d9dcdeb900bc7a. As a bonus, it keeps track on options and update itself if they were changed.

Or you could make a pull request with your changes and make it easier for people to use your code.
