### ISSUE TITLE
Unescape option title

### ISSUE THREAD

**Issue by molbi** [rhyek/vue2-selectize#4]
hi, i have a problem with unescape string for option name. 

here is my code: 

```
<selectize id="service.serviceGroup_id" v-model="service.serviceGroup_id">
<option v-for="o in resources.groups" :value="o.id" v-html="o.title"></option>
</selectize>
```

Result of this is null as title, value of option is ok.

Unfortunately in vue2 is triple bracket {{{ }}} deprecated.

Thank you for help.

**Comment by rhyek** [comment]
Hi. This sounds more like an issue you want to resolve using the VueJS forums. Do you have a Codepen I could review?
