### ISSUE TITLE
Best way to set old value?

### ISSUE THREAD

**Issue by gmask** [rhyek/vue2-selectize#5]
In the case that the form has not been submitted having the placeholder is fine, however I'd like to re-select the previously selected value post-submit. How can I do this?

**Comment by djereg** [comment]
https://github.com/rhyek/vue2-selectize/blob/ff5f09d591d44a8c5b5b5721c67358ea8400883a/src/main.vue#L24-L27

**Comment by rhyek** [comment]
The component respects whatever you change your v-model to.

**Comment by gmask** [comment]
Unfortunately this doesn't appear to work with the `load` option populating the list from a remote API call, how can I use `refreshItems()` on the select after the `load` call has been made? Will this re-render everything with my values selected? https://github.com/selectize/selectize.js/blob/master/docs/api.md

**Comment by rhyek** [comment]
This component only works with `<option>`s rendered in the template. The options should be rendered from a collection you specify using `<option v-for="...">`. What I think you should be able to do is use the `load(query, callback)` option and in your callback you could update that collection with the result from the server.

I have never used that option, but the code should be easy to figure out on your own.

**Comment by gmask** [comment]
Hmm, I'm really not sure what you mean. By just using the `load` option with an axios call and then `callback(response.data)` my list is being built, not with any option tags or v-fors.

Out of curiosity I did remove the load call and made my template look like this:
```
<template>
    <selectize v-model="selected" :settings="settings">
        <option :value="option.ClassCode" v-for="option in options">{{ option.Name }} {{ option.Description }}</option>
    </selectize>
</template>
```

No the `options` array is being built by a normal Vue method using axios, but the list is not being updated when it is complete.

**Comment by rhyek** [comment]
I meant something like this:

```html
<template>
  <selectize v-model="selected" :settings="settings">
    <option v-for="option of options" :value="option">
      {{ option }}
    </option>
  </selectize>
</template>

<script>
export default {
  data () {
    return {
      options: [],
      settings: {
        load: async (query, callback) => {
          // fetch data
          this.options = response
        }
      }
    }
  }
}
</script>
```

**Comment by gmask** [comment]
Thanks very much, your solution works wonderfully!

**Comment by gmask** [comment]
Fix one problem, find another! The issue now is that the `render` method is not longer receiving the original object, just the two HTML attributes of the `<option>`, `value` and `text`. I'd like to be able to use all of the original JSON object's properties in the render function. Looking at the selectize usage guide there is a `dataAttr` option, but binding `:data-data="option"` still doesn't seem to pass the extra data needed for render to the function.

**Comment by rhyek** [comment]
Sorry, buddy. You're gonna have to figure this out on your own. Good luck! I'm sure you can do it.

**Comment by Skintillion** [comment]
I'm using the load option, but manually inserting the initial record as an option.
